### PR TITLE
Add Russian translate

### PR DESCRIPTION
**Pull request by camellan**

### CODE REVIEW

**Comment by bitseater** [comment]
Спасибо

**Comment by camellan** [comment]
Hello. Why not change the program interface language. The cause of could not find.                                                                                                                                                                                                   С уважением,                Культяпов Андрей.                                                                                                                                                                                                                  От: Carlos SuárezОтправлено: воскресенье, 3 декабря 2017 г., 15:10Кому: bitseater/weatherОтветить: bitseater/weatherКопия: Camellan; AuthorТема: Re: [bitseater/weather] Add Russian translate (#13)Merged #13.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bitseater/weather","title":"bitseater/weather","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bitseater/weather"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Merged #13."}],"action":{"name":"View Pull Request","url":"https://github.com/bitseater/weather/pull/13#event-1369215221"}}}

**Comment by bitseater** [comment]
Hello @camellan . Which language? Vala or english? Why (and where) can't you find it?. Thanks for your support and comments.

**Comment by camellan** [comment]
‎I have added Russian language in the program, compiled, installed, launched, and the program interface is in English.                                                                                                                                                                                                                                                                                                                                         С уважением,                Культяпов Андрей.                                                                                                                                                                                                                  От: Carlos SuárezОтправлено: понедельник, 4 декабря 2017 г., 12:27Кому: bitseater/weatherОтветить: bitseater/weatherКопия: Camellan; MentionТема: Re: [bitseater/weather] Add Russian translate (#13)Hello @camellan . Which language? Vala or english? Why (and where) can't you find it?. Thanks for your support and comments.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bitseater/weather","title":"bitseater/weather","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bitseater/weather"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bitseater in #13: Hello @camellan . Which language? Vala or english? Why (and where) can't you find it?. Thanks for your support and comments."}],"action":{"name":"View Pull Request","url":"https://github.com/bitseater/weather/pull/13#issuecomment-348892287"}}}

**Pull request merged**
