### PR TITLE
Updates fr.po

### PR DESCRIPTION
**Pull request by ArthurS1**
Several fixes and improvements over the last version.

### CODE REVIEW

**Comment by ArthurS1** [comment]
Sorry for being this late :/ I might still make improvements once i'll see the translation in their context late.

**Comment by bitseater** [comment]
Don't worry @ArthurS1 , I'll make another release to reorganize all the translatable strings, avoiding similar ones and adding new features in two weeks, in order to be ready to Ubuntu 18.04 release. I will let you know it with more time.

**Comment by bitseater** [comment]
Merçi beaucoup, mon ami.

**Comment by ArthurS1** [comment]
De rien :D

**Pull request merged**
